# MaxNet
MaxNet is a neural network which can find the biggest number in a list of numbers.

In [9]:
## Assume we wanna find the maximum in the following list [1.2, 1.1, 1 , 0.9, 0.95 , 1.15]
## By doing some modification on this network we can also specify the order of numbers in ascending or descending mode
## and also we can make a MinNet
## Epslion should be a number smaller the ( 1 / length of the list)

import numpy as np
X=np.array([1.2, 1.1, 1 , 0.9, 0.95 , 1.15])
eps=0.15
W=np.eye(6,6)
for i in range(6):
  for j in range(6):
    if i!=j:
      W[i,j]=-eps
print("x = ")
print(X)
print("**************************** ")
print("W = ")
print(W)

x = 
[1.2  1.1  1.   0.9  0.95 1.15]
**************************** 
W = 
[[ 1.   -0.15 -0.15 -0.15 -0.15 -0.15]
 [-0.15  1.   -0.15 -0.15 -0.15 -0.15]
 [-0.15 -0.15  1.   -0.15 -0.15 -0.15]
 [-0.15 -0.15 -0.15  1.   -0.15 -0.15]
 [-0.15 -0.15 -0.15 -0.15  1.   -0.15]
 [-0.15 -0.15 -0.15 -0.15 -0.15  1.  ]]


In [10]:
# Activation Function
def act(x, th=0):
  if x>=th:
    return x
  else: return 0

#MaxNet
def maxnet( X , th , eps , show):
  stop=False
  A=np.copy(X)
  A_old=np.copy(A)
  while stop==False :
    for i in range(X.shape[0]):
      A[i]=act ( A_old[i] - eps*(sum(A_old)-A_old[i]) , th=th)
    A_old=np.copy(A)
    if show==True :
      print(A)
    if np.count_nonzero(A)==1:
      stop=True
      max_arg=np.array(np.argwhere(A!=0)).ravel()
      max=np.array(X[max_arg]).ravel()
      if show==True:
        print("MAX : " + str(max) )
  return max, max_arg

#Descending Order
def max_order(X,th,eps):
  y=np.copy(X)
  order=[]
  for i in range(y.shape[0]):
    max , max_arg=maxnet( X=y , th=th , eps=eps , show=False)
    order.append(max)
    y=np.delete(y, max_arg)
  print(order)

#Ascending Order
def min_order(X,th,eps):
  y=1/np.copy(X)
  order=[]
  for i in range(y.shape[0]):
    max , max_arg=maxnet( X=y , th=th , eps=eps , show=False)
    order.append(1/max)
    y=np.delete(y, max_arg)
  print(order)

In [11]:
eps=0.15
th=0
maxnet( X , th=th , eps=eps,show=True)

[0.435  0.32   0.205  0.09   0.1475 0.3775]
[0.264    0.13175  0.       0.       0.       0.197875]
[0.21455625 0.06246875 0.         0.         0.         0.1385125 ]
[0.18440906 0.00950844 0.         0.         0.         0.09695875]
[0.16843898 0.         0.         0.         0.         0.06787112]
[0.15825832 0.         0.         0.         0.         0.04260528]
[0.15186752 0.         0.         0.         0.         0.01886653]
[0.14903754 0.         0.         0.         0.         0.        ]
MAX : [1.2]


(array([1.2]), array([0], dtype=int64))

In [12]:
max_order(X=X,th=0,eps=eps)

[array([1.2]), array([1.15]), array([1.1]), array([1.]), array([0.95]), array([0.9])]


In [13]:
min_order(X=X,th=0,eps=eps)

[array([0.9]), array([0.95]), array([1.]), array([1.1]), array([1.15]), array([1.2])]
